parameters:
#    cms_content.example.class: CMS\ContentBundle\Example

services:
#    cms_content.example:
#        class: %cms_content.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    cms_content.upload_listener:
        class: CMS\ContentBundle\EventListener\UploadListener
        arguments: ['@doctrine']
        tags:
           - { name: kernel.event_listener, event: oneup_uploader.post_persist, method: onUpload }