<?php

namespace CMS\TeamBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NewsAttachmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsAttachmentRepository extends EntityRepository
{
}
