<?php

namespace CMS\ContentBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategoriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriesRepository extends EntityRepository
{
    public function getContentItemsForCategoryIdAndLanguage($categoryId, $language, $offset = null)
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery("SELECT c FROM CMSContentBundle:Content c JOIN c.categories m WHERE m.id = " . $categoryId . " AND c.language = '" . $language . "' ORDER BY c.id DESC");
        if($offset){
            $query->setMaxResults($offset);
        }
        $contentItems = $query->getResult();

        return $contentItems;
    }

    public function getFrontendContentItemsForCategoryIdAndLanguage($categoryId, $language, $offset = null)
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery("SELECT c FROM CMSContentBundle:Content c JOIN c.categories m WHERE m.id = " . $categoryId . " AND c.language = '" . $language . "' AND c.published = 1 ORDER BY c.id DESC");

        if($offset){
            $query->setMaxResults($offset);
        }

        $contentItems = $query->getResult();

        return $contentItems;
    }

    public function getFrontendContentItemsForCategoryIdMonthAndLanguage($categoryId, $language, $month)
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery("SELECT c FROM CMSContentBundle:Content c JOIN c.categories m WHERE m.id = " . $categoryId . " AND c.language = '" . $language . "' AND c.published = 1 AND c.created > :limit")->setParameter('limit', new \DateTime('today ' . $month . ' months ago'));

        $contentItems = $query->getResult();

        return $contentItems;
    }

    public function getOnlyContentItemsForCategoryIdAndLanguage($categoryId, $language)
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery("SELECT c FROM CMSContentBundle:Content c JOIN c.categories m WHERE m.id = " . $categoryId . " AND c.language = '" . $language . "'");

        $contentItems = $query->getResult();

        return $contentItems;
    }
}
