<?php

namespace CMS\ContentBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ContentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContentRepository extends EntityRepository
{
	public function getContentItemsforMenuItemIDandPosition($menuKeyid, $position, $language) {
		$em = $this->getEntityManager();
		$query = $em->createQuery("SELECT c,k,p FROM CMSContentBundle:ContentPosition m
									JOIN CMSContentBundle:Content c
									WITH m.contentKey = c.contentKey
									JOIN c.contentKey k
									JOIN k.contentType p
									WHERE m.menuKey =".$menuKeyid."
										AND m.position =".$position." 
										AND c.language = '".$language."'
									ORDER BY m.ordering ASC");
		$contentItems = $query->getResult();
		
		return $contentItems;
	}
}
