<?php

namespace CMS\ContentBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MenuItemsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuItemsRepository extends EntityRepository
{
	public function getParentMenuItems($id, $language) {
		$em = $this->getEntityManager();
		$query = $em->createQuery("SELECT m FROM CMSContentBundle:MenuItems m JOIN m.menuKey k WHERE k.parentItem is NULL AND m.menu =".$id." AND m.language = '".$language."' ORDER BY k.parentOrdering, k.ordering ASC");
		$menuItems = $query->getResult();
		
		return $menuItems;
	}
	
	public function getChildrenMenuItems($id, $itemid, $language) {
		$em = $this->getEntityManager();
		$query = $em->createQuery("SELECT m FROM CMSContentBundle:MenuItems m JOIN m.menuKey k WHERE k.parentItem =".$itemid." AND m.menu =".$id." AND m.language = '".$language."' ORDER BY k.ordering ASC");
		$menuItems = $query->getResult();
		
		return $menuItems;
	}
}