<?php

namespace CMS\ContentBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MenuKeyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuKeyRepository extends EntityRepository
{
	public function getChildrenOrdering($id, $itemid, $language) {
		$em = $this->getEntityManager();
		$query = $em->createQuery("SELECT k FROM CMSContentBundle:MenuKey k JOIN k.menuItems m WHERE k.parentItem =".$itemid." AND m.menu =".$id." AND m.language = '".$language."' ORDER BY k.ordering ASC");
		$menuItems = $query->getResult();
		
		return $menuItems;
	}

    public function getMenu($id, $language) {
        $em = $this->getEntityManager();
        $query = $em->createQuery("SELECT k, m , c, cm FROM CMSContentBundle:MenuKey k JOIN k.menuItems m LEFT JOIN k.children c LEFT JOIN c.menuItems cm WHERE m.menu = ".$id." and m.language = '".$language."' and (cm.language = '".$language."' or cm.language is NULL) and k.parentOrdering != 0 ORDER BY k.parentOrdering, c.ordering ASC");
        $menuItems = $query->getResult();

        return $menuItems;
    }

    public function getChildrenMenuKeys($id, $itemid, $language) {
        $em = $this->getEntityManager();
        $query = $em->createQuery("SELECT k, m FROM CMSContentBundle:MenuKey k JOIN k.menuItems m WHERE k.parentItem =".$itemid." AND m.menu =".$id." AND m.language = '".$language."' ORDER BY k.ordering ASC");
        $menuItems = $query->getResult();

        return $menuItems;
    }
}
