<?php

namespace CMS\ContentBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MenusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenusRepository extends EntityRepository
{
	public function getParentMenuItems($id)
    {
        return $this->getEntityManager()
			->createQuerry('SELECT p FROM CMS:ContentBundle:Menus p WHERE p.parent_id = NULL')
			->getResult();
    }
}
