CMS\CareerBundle\Entity\Resume:
    type: entity
    table: CMS_resume
    repositoryClass: CMS\ContentBundle\Entity\ContentRepository
    id:
        id:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: IDENTITY
    fields:
        added:
            type: datetime
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
        name:
            type: string
            scale: 0
            length: 200
            unique: false
            nullable: false
            precision: 0
        dreamjob:
            type: string
            scale: 0
            length: 200
            unique: false
            nullable: false
            precision: 0
        email:
            type: string
            scale: 0
            length: 200
            unique: false
            nullable: false
            precision: 0
        description:
            type: string
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
        path:
            type: string
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
    lifecycleCallbacks: {  }
